/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 17
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_EQ = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COMMA = 5,
  sym_int = 6,
  anon_sym_DQUOTE = 7,
  sym_string_raw = 8,
  sym_string_escape = 9,
  sym_name = 10,
  anon_sym_DOT = 11,
  anon_sym_DOT_AT = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_AT = 15,
  anon_sym_DASH_GT = 16,
  sym_source_file = 17,
  sym_assign = 18,
  sym_scope = 19,
  sym_set = 20,
  sym_value = 21,
  sym_string = 22,
  sym_string_content = 23,
  sym_call = 24,
  sym_find = 25,
  sym_find_meta = 26,
  sym_bracket = 27,
  sym_meta = 28,
  sym_function = 29,
  sym_trivial = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_set_repeat1 = 32,
  aux_sym_string_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_raw] = "string_raw",
  [sym_string_escape] = "string_escape",
  [sym_name] = "name",
  [anon_sym_DOT] = ".",
  [anon_sym_DOT_AT] = ".@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_AT] = "@",
  [anon_sym_DASH_GT] = "->",
  [sym_source_file] = "source_file",
  [sym_assign] = "assign",
  [sym_scope] = "scope",
  [sym_set] = "set",
  [sym_value] = "value",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [sym_call] = "call",
  [sym_find] = "find",
  [sym_find_meta] = "find_meta",
  [sym_bracket] = "bracket",
  [sym_meta] = "meta",
  [sym_function] = "function",
  [sym_trivial] = "trivial",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_raw] = sym_string_raw,
  [sym_string_escape] = sym_string_escape,
  [sym_name] = sym_name,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOT_AT] = anon_sym_DOT_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_source_file] = sym_source_file,
  [sym_assign] = sym_assign,
  [sym_scope] = sym_scope,
  [sym_set] = sym_set,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [sym_call] = sym_call,
  [sym_find] = sym_find,
  [sym_find_meta] = sym_find_meta,
  [sym_bracket] = sym_bracket,
  [sym_meta] = sym_meta,
  [sym_function] = sym_function,
  [sym_trivial] = sym_trivial,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_find] = {
    .visible = true,
    .named = true,
  },
  [sym_find_meta] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_meta] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_trivial] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assign = 1,
  field_content = 2,
  field_func = 3,
  field_in_ = 4,
  field_key = 5,
  field_name = 6,
  field_param = 7,
  field_scope = 8,
  field_value = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assign] = "assign",
  [field_content] = "content",
  [field_func] = "func",
  [field_in_] = "in_",
  [field_key] = "key",
  [field_name] = "name",
  [field_param] = "param",
  [field_scope] = "scope",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 1},
  [7] = {.index = 8, .length = 2},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 1},
  [10] = {.index = 12, .length = 1},
  [11] = {.index = 13, .length = 2},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 2},
  [14] = {.index = 18, .length = 2},
  [15] = {.index = 20, .length = 1},
  [16] = {.index = 21, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assign, 0, .inherited = true},
  [1] =
    {field_assign, 0},
  [2] =
    {field_assign, 0, .inherited = true},
    {field_assign, 1, .inherited = true},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_content, 0},
  [7] =
    {field_name, 1},
  [8] =
    {field_func, 0},
    {field_param, 1},
  [10] =
    {field_key, 0},
  [11] =
    {field_assign, 1, .inherited = true},
  [12] =
    {field_key, 1, .inherited = true},
  [13] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
  [15] =
    {field_content, 1, .inherited = true},
  [16] =
    {field_content, 0, .inherited = true},
    {field_content, 1, .inherited = true},
  [18] =
    {field_in_, 0},
    {field_scope, 2},
  [20] =
    {field_value, 1},
  [21] =
    {field_name, 2},
    {field_value, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 13,
        '(', 20,
        ')', 21,
        '+', 3,
        ',', 11,
        '-', 2,
        '.', 18,
        ';', 7,
        '=', 8,
        '@', 22,
        '\\', 4,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 13,
        '(', 20,
        ')', 21,
        '+', 3,
        ',', 11,
        '-', 2,
        ';', 7,
        '=', 8,
        '@', 22,
        '{', 9,
        '}', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string_raw);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string_raw);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '@') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_DOT_AT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOT_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_assign] = STATE(42),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_scope] = STATE(9),
    [sym_set] = STATE(9),
    [sym_value] = STATE(2),
    [sym_string] = STATE(9),
    [sym_call] = STATE(9),
    [sym_find] = STATE(9),
    [sym_find_meta] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_meta] = STATE(9),
    [sym_function] = STATE(9),
    [sym_trivial] = STATE(9),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_DOT_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(7),
    [anon_sym_AT] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym_scope] = STATE(9),
    [sym_set] = STATE(9),
    [sym_value] = STATE(2),
    [sym_string] = STATE(9),
    [sym_call] = STATE(9),
    [sym_find] = STATE(9),
    [sym_find_meta] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_meta] = STATE(9),
    [sym_function] = STATE(9),
    [sym_trivial] = STATE(9),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_DOT_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_AT] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym_scope] = STATE(9),
    [sym_set] = STATE(9),
    [sym_value] = STATE(2),
    [sym_string] = STATE(9),
    [sym_call] = STATE(9),
    [sym_find] = STATE(9),
    [sym_find_meta] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_meta] = STATE(9),
    [sym_function] = STATE(9),
    [sym_trivial] = STATE(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_DOT_AT] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_AT] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym_scope] = STATE(9),
    [sym_set] = STATE(9),
    [sym_value] = STATE(4),
    [sym_string] = STATE(9),
    [sym_call] = STATE(9),
    [sym_find] = STATE(9),
    [sym_find_meta] = STATE(9),
    [sym_bracket] = STATE(9),
    [sym_meta] = STATE(9),
    [sym_function] = STATE(9),
    [sym_trivial] = STATE(9),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_AT] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      sym_name,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      anon_sym_AT,
    STATE(3), 1,
      sym_value,
    STATE(9), 10,
      sym_scope,
      sym_set,
      sym_string,
      sym_call,
      sym_find,
      sym_find_meta,
      sym_bracket,
      sym_meta,
      sym_function,
      sym_trivial,
  [34] = 3,
    ACTIONS(33), 1,
      anon_sym_DOT,
    ACTIONS(35), 1,
      anon_sym_DASH_GT,
    ACTIONS(31), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [52] = 2,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(37), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [67] = 2,
    ACTIONS(33), 1,
      anon_sym_DOT,
    ACTIONS(31), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [82] = 2,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(41), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [97] = 2,
    ACTIONS(47), 1,
      anon_sym_DOT,
    ACTIONS(45), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [112] = 2,
    ACTIONS(51), 1,
      anon_sym_DOT,
    ACTIONS(49), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [127] = 2,
    ACTIONS(55), 1,
      anon_sym_DOT,
    ACTIONS(53), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [142] = 2,
    ACTIONS(59), 1,
      anon_sym_DOT,
    ACTIONS(57), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [157] = 2,
    ACTIONS(63), 1,
      anon_sym_DOT,
    ACTIONS(61), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [172] = 2,
    ACTIONS(67), 1,
      anon_sym_DOT,
    ACTIONS(65), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [187] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(69), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [202] = 2,
    ACTIONS(75), 1,
      anon_sym_DOT,
    ACTIONS(73), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [217] = 2,
    ACTIONS(79), 1,
      anon_sym_DOT,
    ACTIONS(77), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [232] = 2,
    ACTIONS(83), 1,
      anon_sym_DOT,
    ACTIONS(81), 9,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      sym_int,
      anon_sym_DQUOTE,
      sym_name,
      anon_sym_DOT_AT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_AT,
  [247] = 6,
    ACTIONS(85), 1,
      anon_sym_EQ,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(89), 1,
      sym_name,
    STATE(27), 1,
      aux_sym_source_file_repeat1,
    STATE(30), 1,
      aux_sym_set_repeat1,
    STATE(42), 1,
      sym_assign,
  [266] = 4,
    ACTIONS(91), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_string_repeat1,
    STATE(33), 1,
      sym_string_content,
    ACTIONS(93), 2,
      sym_string_raw,
      sym_string_escape,
  [280] = 4,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      aux_sym_string_repeat1,
    STATE(33), 1,
      sym_string_content,
    ACTIONS(93), 2,
      sym_string_raw,
      sym_string_escape,
  [294] = 4,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_string_repeat1,
    STATE(33), 1,
      sym_string_content,
    ACTIONS(99), 2,
      sym_string_raw,
      sym_string_escape,
  [308] = 4,
    ACTIONS(104), 1,
      sym_name,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    STATE(42), 1,
      sym_assign,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [322] = 4,
    ACTIONS(5), 1,
      sym_name,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    STATE(42), 1,
      sym_assign,
  [335] = 4,
    ACTIONS(5), 1,
      sym_name,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    STATE(25), 1,
      aux_sym_source_file_repeat1,
    STATE(42), 1,
      sym_assign,
  [348] = 4,
    ACTIONS(5), 1,
      sym_name,
    ACTIONS(85), 1,
      anon_sym_EQ,
    STATE(27), 1,
      aux_sym_source_file_repeat1,
    STATE(42), 1,
      sym_assign,
  [361] = 3,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(113), 1,
      sym_name,
    STATE(29), 1,
      aux_sym_set_repeat1,
  [371] = 3,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 1,
      sym_name,
    STATE(29), 1,
      aux_sym_set_repeat1,
  [381] = 1,
    ACTIONS(120), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_name,
  [387] = 2,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    ACTIONS(124), 2,
      sym_string_raw,
      sym_string_escape,
  [395] = 2,
    ACTIONS(126), 1,
      anon_sym_DQUOTE,
    ACTIONS(128), 2,
      sym_string_raw,
      sym_string_escape,
  [403] = 1,
    ACTIONS(130), 2,
      anon_sym_RBRACE,
      sym_name,
  [408] = 2,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_scope,
  [415] = 2,
    ACTIONS(134), 1,
      anon_sym_EQ,
    ACTIONS(136), 1,
      anon_sym_COMMA,
  [422] = 1,
    ACTIONS(138), 1,
      sym_name,
  [426] = 1,
    ACTIONS(140), 1,
      ts_builtin_sym_end,
  [430] = 1,
    ACTIONS(142), 1,
      sym_name,
  [434] = 1,
    ACTIONS(144), 1,
      anon_sym_RBRACE,
  [438] = 1,
    ACTIONS(136), 1,
      anon_sym_COMMA,
  [442] = 1,
    ACTIONS(146), 1,
      anon_sym_SEMI,
  [446] = 1,
    ACTIONS(134), 1,
      anon_sym_EQ,
  [450] = 1,
    ACTIONS(148), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 34,
  [SMALL_STATE(8)] = 52,
  [SMALL_STATE(9)] = 67,
  [SMALL_STATE(10)] = 82,
  [SMALL_STATE(11)] = 97,
  [SMALL_STATE(12)] = 112,
  [SMALL_STATE(13)] = 127,
  [SMALL_STATE(14)] = 142,
  [SMALL_STATE(15)] = 157,
  [SMALL_STATE(16)] = 172,
  [SMALL_STATE(17)] = 187,
  [SMALL_STATE(18)] = 202,
  [SMALL_STATE(19)] = 217,
  [SMALL_STATE(20)] = 232,
  [SMALL_STATE(21)] = 247,
  [SMALL_STATE(22)] = 266,
  [SMALL_STATE(23)] = 280,
  [SMALL_STATE(24)] = 294,
  [SMALL_STATE(25)] = 308,
  [SMALL_STATE(26)] = 322,
  [SMALL_STATE(27)] = 335,
  [SMALL_STATE(28)] = 348,
  [SMALL_STATE(29)] = 361,
  [SMALL_STATE(30)] = 371,
  [SMALL_STATE(31)] = 381,
  [SMALL_STATE(32)] = 387,
  [SMALL_STATE(33)] = 395,
  [SMALL_STATE(34)] = 403,
  [SMALL_STATE(35)] = 408,
  [SMALL_STATE(36)] = 415,
  [SMALL_STATE(37)] = 422,
  [SMALL_STATE(38)] = 426,
  [SMALL_STATE(39)] = 430,
  [SMALL_STATE(40)] = 434,
  [SMALL_STATE(41)] = 438,
  [SMALL_STATE(42)] = 442,
  [SMALL_STATE(43)] = 446,
  [SMALL_STATE(44)] = 450,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, 0, 10),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3, 0, 10),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trivial, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trivial, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta, 2, 0, 6),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meta, 2, 0, 6),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 9),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 9),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 3, 0, 15),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket, 3, 0, 15),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find, 3, 0, 16),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find, 3, 0, 16),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 12),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 12),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3, 0, 14),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3, 0, 14),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_meta, 3, 0, 16),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_meta, 3, 0, 16),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 13),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 13), SHIFT_REPEAT(32),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(43),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 11),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 11), SHIFT_REPEAT(41),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_content, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_content, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 5),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 8),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [140] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_moss(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "moss",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
