/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_EQ = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_COMMA = 5,
  anon_sym_COLON = 6,
  sym_int = 7,
  anon_sym_DQUOTE = 8,
  sym_string_raw = 9,
  sym_string_escape = 10,
  sym_name = 11,
  sym_builtin_if = 12,
  sym_builtin_add = 13,
  sym_builtin_mod = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  sym_source_file = 17,
  sym_assign = 18,
  sym_scope = 19,
  sym_set = 20,
  sym_pair = 21,
  sym_dict = 22,
  sym_value = 23,
  sym_string = 24,
  sym_string_content = 25,
  sym_builtin = 26,
  sym_call = 27,
  sym_find = 28,
  sym_bracket = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_set_repeat1 = 31,
  aux_sym_dict_repeat1 = 32,
  aux_sym_string_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_int] = "int",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_raw] = "string_raw",
  [sym_string_escape] = "string_escape",
  [sym_name] = "name",
  [sym_builtin_if] = "builtin_if",
  [sym_builtin_add] = "builtin_add",
  [sym_builtin_mod] = "builtin_mod",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym_assign] = "assign",
  [sym_scope] = "scope",
  [sym_set] = "set",
  [sym_pair] = "pair",
  [sym_dict] = "dict",
  [sym_value] = "value",
  [sym_string] = "string",
  [sym_string_content] = "string_content",
  [sym_builtin] = "builtin",
  [sym_call] = "call",
  [sym_find] = "find",
  [sym_bracket] = "bracket",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_set_repeat1] = "set_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_int] = sym_int,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_raw] = sym_string_raw,
  [sym_string_escape] = sym_string_escape,
  [sym_name] = sym_name,
  [sym_builtin_if] = sym_builtin_if,
  [sym_builtin_add] = sym_builtin_add,
  [sym_builtin_mod] = sym_builtin_mod,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_assign] = sym_assign,
  [sym_scope] = sym_scope,
  [sym_set] = sym_set,
  [sym_pair] = sym_pair,
  [sym_dict] = sym_dict,
  [sym_value] = sym_value,
  [sym_string] = sym_string,
  [sym_string_content] = sym_string_content,
  [sym_builtin] = sym_builtin,
  [sym_call] = sym_call,
  [sym_find] = sym_find,
  [sym_bracket] = sym_bracket,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_set_repeat1] = aux_sym_set_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_string_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_if] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_add] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_mod] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_scope] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_find] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assign = 1,
  field_content = 2,
  field_func = 3,
  field_key = 4,
  field_name = 5,
  field_pair = 6,
  field_param = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assign] = "assign",
  [field_content] = "content",
  [field_func] = "func",
  [field_key] = "key",
  [field_name] = "name",
  [field_pair] = "pair",
  [field_param] = "param",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 2},
  [13] = {.index = 17, .length = 1},
  [14] = {.index = 18, .length = 2},
  [15] = {.index = 20, .length = 1},
  [16] = {.index = 21, .length = 2},
  [17] = {.index = 23, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assign, 0, .inherited = true},
  [1] =
    {field_assign, 0},
  [2] =
    {field_assign, 0, .inherited = true},
    {field_assign, 1, .inherited = true},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_content, 0},
  [7] =
    {field_name, 1},
    {field_value, 0},
  [9] =
    {field_func, 0},
    {field_param, 1},
  [11] =
    {field_key, 0},
  [12] =
    {field_pair, 0},
  [13] =
    {field_assign, 1, .inherited = true},
  [14] =
    {field_key, 1, .inherited = true},
  [15] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
  [17] =
    {field_pair, 1, .inherited = true},
  [18] =
    {field_pair, 0, .inherited = true},
    {field_pair, 1, .inherited = true},
  [20] =
    {field_content, 1, .inherited = true},
  [21] =
    {field_content, 0, .inherited = true},
    {field_content, 1, .inherited = true},
  [23] =
    {field_value, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 14,
        '(', 27,
        ')', 28,
        ',', 11,
        ':', 12,
        ';', 7,
        '=', 8,
        '\\', 3,
        'a', 20,
        'i', 21,
        'm', 22,
        '{', 9,
        '}', 10,
        '+', 2,
        '-', 2,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead == '\\') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 4:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 14,
        '(', 27,
        ')', 28,
        ',', 11,
        ':', 12,
        ';', 7,
        '=', 8,
        'a', 20,
        'i', 21,
        'm', 22,
        '{', 9,
        '}', 10,
        '+', 2,
        '-', 2,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '}') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_string_raw);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_string_raw);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string_escape);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'd') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'd') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'd') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'o') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_builtin_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_builtin_add);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_builtin_mod);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_escape] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_builtin_if] = ACTIONS(1),
    [sym_builtin_add] = ACTIONS(1),
    [sym_builtin_mod] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_assign] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_scope] = STATE(14),
    [sym_set] = STATE(14),
    [sym_dict] = STATE(14),
    [sym_value] = STATE(2),
    [sym_string] = STATE(14),
    [sym_builtin] = STATE(14),
    [sym_call] = STATE(14),
    [sym_find] = STATE(14),
    [sym_bracket] = STATE(14),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(7),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [sym_builtin_if] = ACTIONS(17),
    [sym_builtin_add] = ACTIONS(17),
    [sym_builtin_mod] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_scope] = STATE(14),
    [sym_set] = STATE(14),
    [sym_dict] = STATE(14),
    [sym_value] = STATE(2),
    [sym_string] = STATE(14),
    [sym_builtin] = STATE(14),
    [sym_call] = STATE(14),
    [sym_find] = STATE(14),
    [sym_bracket] = STATE(14),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [sym_builtin_if] = ACTIONS(17),
    [sym_builtin_add] = ACTIONS(17),
    [sym_builtin_mod] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
  },
  [STATE(4)] = {
    [sym_scope] = STATE(14),
    [sym_set] = STATE(14),
    [sym_dict] = STATE(14),
    [sym_value] = STATE(2),
    [sym_string] = STATE(14),
    [sym_builtin] = STATE(14),
    [sym_call] = STATE(14),
    [sym_find] = STATE(14),
    [sym_bracket] = STATE(14),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [sym_builtin_if] = ACTIONS(17),
    [sym_builtin_add] = ACTIONS(17),
    [sym_builtin_mod] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
    [anon_sym_RPAREN] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym_scope] = STATE(14),
    [sym_set] = STATE(14),
    [sym_dict] = STATE(14),
    [sym_value] = STATE(2),
    [sym_string] = STATE(14),
    [sym_builtin] = STATE(14),
    [sym_call] = STATE(14),
    [sym_find] = STATE(14),
    [sym_bracket] = STATE(14),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_COMMA] = ACTIONS(25),
    [sym_int] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [sym_name] = ACTIONS(15),
    [sym_builtin_if] = ACTIONS(17),
    [sym_builtin_add] = ACTIONS(17),
    [sym_builtin_mod] = ACTIONS(17),
    [anon_sym_LPAREN] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_name,
    STATE(5), 1,
      sym_value,
    ACTIONS(17), 3,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    STATE(14), 8,
      sym_scope,
      sym_set,
      sym_dict,
      sym_string,
      sym_builtin,
      sym_call,
      sym_find,
      sym_bracket,
  [34] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_name,
    STATE(4), 1,
      sym_value,
    ACTIONS(17), 3,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    STATE(14), 8,
      sym_scope,
      sym_set,
      sym_dict,
      sym_string,
      sym_builtin,
      sym_call,
      sym_find,
      sym_bracket,
  [68] = 8,
    ACTIONS(9), 1,
      anon_sym_LBRACE,
    ACTIONS(11), 1,
      sym_int,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_name,
    STATE(3), 1,
      sym_value,
    ACTIONS(17), 3,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    STATE(14), 8,
      sym_scope,
      sym_set,
      sym_dict,
      sym_string,
      sym_builtin,
      sym_call,
      sym_find,
      sym_bracket,
  [102] = 2,
    ACTIONS(31), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(29), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [118] = 2,
    ACTIONS(35), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(33), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [134] = 2,
    ACTIONS(39), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(37), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [150] = 2,
    ACTIONS(43), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(41), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [166] = 2,
    ACTIONS(47), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(45), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [182] = 2,
    ACTIONS(51), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(49), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [198] = 2,
    ACTIONS(55), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(53), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [214] = 2,
    ACTIONS(59), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(57), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [230] = 2,
    ACTIONS(63), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(61), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [246] = 2,
    ACTIONS(67), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(65), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [262] = 2,
    ACTIONS(71), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(69), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [278] = 2,
    ACTIONS(75), 4,
      sym_name,
      sym_builtin_if,
      sym_builtin_add,
      sym_builtin_mod,
    ACTIONS(73), 7,
      anon_sym_SEMI,
      anon_sym_LBRACE,
      anon_sym_COMMA,
      sym_int,
      anon_sym_DQUOTE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [294] = 9,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    ACTIONS(81), 1,
      anon_sym_COLON,
    ACTIONS(83), 1,
      sym_name,
    STATE(28), 1,
      aux_sym_source_file_repeat1,
    STATE(29), 1,
      aux_sym_dict_repeat1,
    STATE(34), 1,
      aux_sym_set_repeat1,
    STATE(43), 1,
      sym_pair,
    STATE(45), 1,
      sym_assign,
  [322] = 4,
    ACTIONS(85), 1,
      anon_sym_DQUOTE,
    STATE(25), 1,
      aux_sym_string_repeat1,
    STATE(32), 1,
      sym_string_content,
    ACTIONS(87), 2,
      sym_string_raw,
      sym_string_escape,
  [336] = 4,
    ACTIONS(89), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      aux_sym_string_repeat1,
    STATE(32), 1,
      sym_string_content,
    ACTIONS(87), 2,
      sym_string_raw,
      sym_string_escape,
  [350] = 4,
    ACTIONS(93), 1,
      sym_name,
    STATE(24), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_assign,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [364] = 4,
    ACTIONS(96), 1,
      anon_sym_DQUOTE,
    STATE(25), 1,
      aux_sym_string_repeat1,
    STATE(32), 1,
      sym_string_content,
    ACTIONS(98), 2,
      sym_string_raw,
      sym_string_escape,
  [378] = 4,
    ACTIONS(5), 1,
      sym_name,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_assign,
  [391] = 4,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(105), 1,
      sym_name,
    STATE(27), 1,
      aux_sym_dict_repeat1,
    STATE(43), 1,
      sym_pair,
  [404] = 4,
    ACTIONS(5), 1,
      sym_name,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(24), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_assign,
  [417] = 4,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 1,
      sym_name,
    STATE(27), 1,
      aux_sym_dict_repeat1,
    STATE(43), 1,
      sym_pair,
  [430] = 2,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 2,
      sym_string_raw,
      sym_string_escape,
  [438] = 3,
    ACTIONS(118), 1,
      anon_sym_EQ,
    ACTIONS(120), 1,
      anon_sym_COMMA,
    ACTIONS(122), 1,
      anon_sym_COLON,
  [448] = 2,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
    ACTIONS(126), 2,
      sym_string_raw,
      sym_string_escape,
  [456] = 1,
    ACTIONS(128), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_name,
  [462] = 3,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(132), 1,
      sym_name,
    STATE(35), 1,
      aux_sym_set_repeat1,
  [472] = 3,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    ACTIONS(136), 1,
      sym_name,
    STATE(35), 1,
      aux_sym_set_repeat1,
  [482] = 1,
    ACTIONS(139), 2,
      anon_sym_RBRACE,
      sym_name,
  [487] = 1,
    ACTIONS(141), 2,
      anon_sym_RBRACE,
      sym_name,
  [492] = 1,
    ACTIONS(143), 1,
      ts_builtin_sym_end,
  [496] = 1,
    ACTIONS(118), 1,
      anon_sym_EQ,
  [500] = 1,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
  [504] = 1,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
  [508] = 1,
    ACTIONS(122), 1,
      anon_sym_COLON,
  [512] = 1,
    ACTIONS(149), 1,
      anon_sym_COMMA,
  [516] = 1,
    ACTIONS(120), 1,
      anon_sym_COMMA,
  [520] = 1,
    ACTIONS(151), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 34,
  [SMALL_STATE(8)] = 68,
  [SMALL_STATE(9)] = 102,
  [SMALL_STATE(10)] = 118,
  [SMALL_STATE(11)] = 134,
  [SMALL_STATE(12)] = 150,
  [SMALL_STATE(13)] = 166,
  [SMALL_STATE(14)] = 182,
  [SMALL_STATE(15)] = 198,
  [SMALL_STATE(16)] = 214,
  [SMALL_STATE(17)] = 230,
  [SMALL_STATE(18)] = 246,
  [SMALL_STATE(19)] = 262,
  [SMALL_STATE(20)] = 278,
  [SMALL_STATE(21)] = 294,
  [SMALL_STATE(22)] = 322,
  [SMALL_STATE(23)] = 336,
  [SMALL_STATE(24)] = 350,
  [SMALL_STATE(25)] = 364,
  [SMALL_STATE(26)] = 378,
  [SMALL_STATE(27)] = 391,
  [SMALL_STATE(28)] = 404,
  [SMALL_STATE(29)] = 417,
  [SMALL_STATE(30)] = 430,
  [SMALL_STATE(31)] = 438,
  [SMALL_STATE(32)] = 448,
  [SMALL_STATE(33)] = 456,
  [SMALL_STATE(34)] = 462,
  [SMALL_STATE(35)] = 472,
  [SMALL_STATE(36)] = 482,
  [SMALL_STATE(37)] = 487,
  [SMALL_STATE(38)] = 492,
  [SMALL_STATE(39)] = 496,
  [SMALL_STATE(40)] = 500,
  [SMALL_STATE(41)] = 504,
  [SMALL_STATE(42)] = 508,
  [SMALL_STATE(43)] = 512,
  [SMALL_STATE(44)] = 516,
  [SMALL_STATE(45)] = 520,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, 0, 7),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 4),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 10),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 10),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_builtin, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_builtin, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, 0, 11),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set, 3, 0, 11),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find, 2, 0, 6),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find, 2, 0, 6),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_scope, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_scope, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3, 0, 13),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 3, 0, 13),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 15),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 15),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 3, 0, 17),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket, 3, 0, 17),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(39),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 16),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 16), SHIFT_REPEAT(30),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 14),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 14), SHIFT_REPEAT(42),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_content, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_content, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1, 0, 5),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 12),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 12), SHIFT_REPEAT(44),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_repeat1, 2, 0, 8),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 9),
  [143] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_moss(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "moss",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
